name: Angularjs CI/CD

on:
  push:
    branches:
      - 'feature/angular'

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ng-easy/npm-install@v2
      - name: npm install and npm run build
        run: |
          npm install
          ng build